import addResultService from './addResult'
import changeCityService from './changeCity'
import changeNameService from './changeName'
import changePhotoService from './changePhoto'
import resetProfileService from './resetProfile'
